#DO NOT EDIT! This file was generated by tf-generator.
locals {
  INJECTED-var-a = "value-a"
  INJECTED-var-b = "value-b"
}

module "mymodule" {
  source = "first/dir"
  var-a  = local.INJECTED-var-a
}

module "second" {
  source = "second/dir"
  var-b  = local.INJECTED-var-b
}
