#DO NOT EDIT! This file was generated by tf-generator.
first-only      = "first"
first-vs-second = "first"
first-vs-third  = "first"
second-only     = "second"
second-vs-third = "second"
third-only      = "third"
