name: Go Build and Publish

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o tf-generator

    - name: Run GoReleaser
      if: startsWith(github.ref, 'refs/tags/')
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
        distribution: goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
