name: Go Build and Publish

on:
  push:
    tags:
      - '*'
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o tf-generator

    - name: Publish Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      id: publish-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          tf-generator
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
